[[Xorg_recordproto]]
arch = "armv7l"
git-tree-sha1 = "519210ee3262846a71242b0d66d4d3ab9677280d"
libc = "glibc"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "37a103d0d49f8aa62f13ca4e078bab120ea39b1b8bb36a9aaa307a3d1dfd9851"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.arm-linux-gnueabihf.tar.gz"
[[Xorg_recordproto]]
arch = "aarch64"
git-tree-sha1 = "f3d5e5d2c2397ce9d9f07a35cf52c649c2d2f409"
libc = "musl"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "549a812c83d449896c30384b2ee2d1603eb971c97139da547920ca269fb584aa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.aarch64-linux-musl.tar.gz"
[[Xorg_recordproto]]
arch = "i686"
git-tree-sha1 = "9810ca68b87eb0c84d0ca818a49d24a84e4e0311"
libc = "musl"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "774dbc2b8a2a0c794e7268b26977642d70810f81f45e9d8343bde5611ef4f043"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.i686-linux-musl.tar.gz"
[[Xorg_recordproto]]
arch = "i686"
git-tree-sha1 = "ea29b1cb3adf1cac1db27b427b4b57e52fd03730"
libc = "glibc"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "24a9e8082c5571e9f6b63f345129ae45561fa50d7ef6215e78cdd2a83097e9c5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.i686-linux-gnu.tar.gz"
[[Xorg_recordproto]]
arch = "x86_64"
git-tree-sha1 = "68417ebef13f5a63b091891bff3a7a72044f3d93"
os = "freebsd"

    [[Xorg_recordproto.download]]
    sha256 = "94ebf90ca708fb6b6acf9ff3f74ce954cb7188ba139d2d102db7d29c88655a36"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_recordproto]]
arch = "powerpc64le"
git-tree-sha1 = "d29e3ac915479fe5a8fd549494c47dffe052cf81"
libc = "glibc"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "1c54314b0f8d354d8d7be58829ec6996b9f2cda40f3d084a9f9d054c84ac2a98"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_recordproto]]
arch = "armv7l"
git-tree-sha1 = "af25cb4e8c42585da27606a80b37af2990ed1098"
libc = "musl"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "b1527055f98ee3b02e7b1571eac1f10cebc054e29d70993faf77d7ad7466f70c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.arm-linux-musleabihf.tar.gz"
[[Xorg_recordproto]]
arch = "aarch64"
git-tree-sha1 = "c286b28fb439385170810a6bac686c44d6a078c6"
libc = "glibc"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "8a59aded14f0fc49e97671166e6e8d23fc9d26f0efd764bd7df347d178907fad"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.aarch64-linux-gnu.tar.gz"
[[Xorg_recordproto]]
arch = "x86_64"
git-tree-sha1 = "4416dcf5dc2dceff5f4f0a490e313fdaa610c050"
libc = "glibc"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "3cdc1da2d9cc3232306df6f17d10de2d2efc29623abf3c8241aa9838715a8018"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.x86_64-linux-gnu.tar.gz"
[[Xorg_recordproto]]
arch = "x86_64"
git-tree-sha1 = "42d74a2c95ff5c40815c5d7126e33acb097d2090"
libc = "musl"
os = "linux"

    [[Xorg_recordproto.download]]
    sha256 = "fa5a8c22563459061135ffa04ac32fb2dd8896732be549daf100c64b8e1eca54"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+0/Xorg_recordproto.v1.14.2.x86_64-linux-musl.tar.gz"
